inherit_from: .rubocop_todo.yml

require:
 - rubocop-rake
 - rubocop-rspec

AllCops:
    NewCops: enable

Layout/LineLength:
  Max: 120

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
